travis:
  secure:
    BINSTAR_TOKEN: CPRriGBQhJsgDfAeWzIDOKn6MeX715NeJVt62blo9FXy4YZFOib2baWxviLkGYlT9JSJMvRKdgaoBD/k2unkSOVnLQNwuxJfO+/eIsyaraVwXFzJqmnz3vR1dsCvkymZ8L+j49HWy6fpNFlm/WSOksqCHmpogpL/yHFa/8WEwtiO2igzzdsMElytCIh4LpJSyMKDvfhYqaM8Rx9d0s69Tp0nD5kfdKa/WSoAUTuHj1FWSs3rClyLvOcw2gIEyWpY/74ErzF521tpDHSP9wi+jewJx01pWo60L2aQL5e1Bb33d273totj1TQ+CpF+5nlCGM7JZ4ZdulgmQwb0gv4MteQxRnHstVMCGYixpHH251oAfGbWA44mQQVrMefh9dWSSs6aNwgtpzBghtc/HLcQhsih5LLNslPZXfrJNBTQr3f4kmdCYdTdLJV6y03l/FOlbE5PAu/v7Z1WyvUlsWW1lp0OPM0bBcUb9dY8Pk2m421lbfqxLgsHvN79DTW+owrMFB2agKyAPMNQFTlVHlTCbn3M3u3ZFWxmtHNUM+JxwuYNmy9Lh9eE+HCrFqj4oMutR2354qwL4ktPNMcdTirP/n90SxHR1qB1GUfAqPbLzg5CssNhB+rIrnZGhlqJ0PfFvBw1leOa9md1r4fyBnl8jesPRVsnjhPeoDc9sZtTJnc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
